"""create economic_series and economic_observations tables

Revision ID: 596d1786d618
Revises: 9850c5403551
Create Date: 2026-05-04 16:24:58.552398

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "596d1786d618"
down_revision: str | Sequence[str] | None = "9850c5403551"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type explicitly so the second create_table can reference
    # it without trying to re-create it (autogenerate emits sa.Enum(...) for
    # both columns, which would cause "type already exists" on the second one).
    data_source = postgresql.ENUM("fred", "ecb", "eurostat", name="data_source", create_type=False)
    data_source.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "economic_series",
        sa.Column("source", data_source, nullable=False),
        sa.Column("series_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("frequency", sa.String(length=10), nullable=False),
        sa.Column("units", sa.String(length=255), nullable=True),
        sa.Column("seasonal_adjustment", sa.String(length=50), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source", "series_id"),
    )
    op.create_table(
        "economic_observations",
        sa.Column("source", data_source, nullable=False),
        sa.Column("series_id", sa.String(length=255), nullable=False),
        sa.Column("observation_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("extra_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source", "series_id"],
            ["economic_series.source", "economic_series.series_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source", "series_id", "observation_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("economic_observations")
    op.drop_table("economic_series")
    # Drop the enum type only after both tables that reference it are gone.
    data_source = postgresql.ENUM("fred", "ecb", "eurostat", name="data_source", create_type=False)
    data_source.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
