"""make fred_series notes column nullable

Revision ID: 9850c5403551
Revises: a1249bd9adc2
Create Date: 2026-04-27 18:19:29.858290

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9850c5403551"
down_revision: str | Sequence[str] | None = "a1249bd9adc2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("fred_series", "notes", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("fred_series", "notes", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
