"""add fred_series and fred_observations tables

Revision ID: a1249bd9adc2
Revises: 801e7c0c0697
Create Date: 2026-04-24 12:08:14.311500

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1249bd9adc2"
down_revision: str | Sequence[str] | None = "801e7c0c0697"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fred_series",
        sa.Column("series_id", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("frequency", sa.String(length=50), nullable=False),
        sa.Column("frequency_short", sa.String(length=5), nullable=False),
        sa.Column("units", sa.String(length=200), nullable=False),
        sa.Column("units_short", sa.String(length=50), nullable=False),
        sa.Column("seasonal_adjustment", sa.String(length=100), nullable=False),
        sa.Column("seasonal_adjustment_short", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("observation_start", sa.Date(), nullable=False),
        sa.Column("observation_end", sa.Date(), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("series_id"),
    )
    op.create_table(
        "fred_observations",
        sa.Column("series_id", sa.String(length=50), nullable=False),
        sa.Column("observation_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("realtime_start", sa.Date(), nullable=False),
        sa.Column("realtime_end", sa.Date(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["series_id"], ["fred_series.series_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("series_id", "observation_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fred_observations")
    op.drop_table("fred_series")
    # ### end Alembic commands ###
